# GitHub Action para gerar um gráfico de contribuições com uma cobra comendo suas contribuições.

# ![gif da cobra](https://github.com/your-user-name/your-user-name/blob/output/github-contribution-grid-snake.gif)

name: Generate Snake

# Controla quando a ação será executada.
on:
  schedule:
      # a cada 12 horas
    - cron: "0 */12 * * *"

  # Este comando permite executar a Ação automaticamente a partir da aba Actions.
  workflow_dispatch:
  
  # Também executar em cada push no branch principal
  push:
    branches:
    - main

# A sequência de execuções neste fluxo de trabalho:
jobs:
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  build:
    # O tipo de runner que o trabalho será executado
    runs-on: ubuntu-latest

    # Os passos representam uma sequência de tarefas que serão executadas como parte do trabalho
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
    
      - name: Gerar os arquivos da cobra em './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |     
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mostrar status da construção
        run: git status

      - name: Enviar novos arquivos para o branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Atualizar animações da cobra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

